swagger: "2.0"
info:
   description: "Radio Bretzel core API reference."
   version: "0.2.0"
   title: "Radio Bretzel core"
   contact:
      email: "radiobretzel@ntymail.com"
   license:
      name: "GPL-3.0"
      url: "https://www.gnu.org/licenses/gpl-3.0.html"
tags:
-  name: "channel"
   description: "Channels are rooms to chat and listen to music with friends !"
-  name: "source"
   description: "Sources are process creating the audio that will be streamed"
schemes:
   - "https"
paths:
   /channel:
      get:
         consumes:
         - "application/json"
         - "application/xml"
         produces:
         - "application/json"
         responses:
            404:
               description: "Not Found"
            405:
               description: "Validation Error: some given arguments were incorrect"
      post:
         consumes:
         - "application/json"
         - "application/xml"
         produces:
         - "application/json"
         responses:
            404:
               description: "Not Found"
            405:
               description: "Validation Error: some given arguments were incorrect"
      put:
         consumes:
         - "application/json"
         - "application/xml"
         produces:
         - "application/json"
         responses:
            404:
               description: "Not Found"
            405:
               description: "Validation Error: some given arguments were incorrect"
      delete:
         consumes:
         - "application/json"
         - "application/xml"
         produces:
         - "application/json"
         responses:
            404:
               description: "Not Found"
            405:
               description: "Validation Error: some given arguments were incorrect"
   /channel/{channelSlug}:
      get:
         consumes:
         - "application/json"
         - "application/xml"
         produces:
         - "application/json"
         responses:
            404:
               description: "Not Found"
            405:
               description: "Validation Error: some given arguments were incorrect"
      post:
         consumes:
         - "application/json"
         - "application/xml"
         produces:
         - "application/json"
         responses:
            404:
               description: "Not Found"
            405:
               description: "Validation Error: some given arguments were incorrect"
      put:
         consumes:
         - "application/json"
         - "application/xml"
         produces:
         - "application/json"
         responses:
            404:
               description: "Not Found"
            405:
               description: "Validation Error: some given arguments were incorrect"
      delete:
         consumes:
         - "application/json"
         - "application/xml"
         produces:
         - "application/json"
         responses:
            404:
               description: "Not Found"
            405:
               description: "Validation Error: some given arguments were incorrect"
   /channel/{channelSlug}/source:
      get:
         consumes:
         - "application/json"
         - "application/xml"
         produces:
         - "application/json"
         responses:
            404:
               description: "Not Found"
            405:
               description: "Validation Error: some given arguments were incorrect"
      post:
         consumes:
         - "application/json"
         - "application/xml"
         produces:
         - "application/json"
         responses:
            404:
               description: "Not Found"
            405:
               description: "Validation Error: some given arguments were incorrect"
      put:
         consumes:
         - "application/json"
         - "application/xml"
         produces:
         - "application/json"
         responses:
            404:
               description: "Not Found"
            405:
               description: "Validation Error: some given arguments were incorrect"
      delete:
         consumes:
         - "application/json"
         - "application/xml"
         produces:
         - "application/json"
         responses:
            404:
               description: "Not Found"
            405:
               description: "Validation Error: some given arguments were incorrect"
   /channel/{channelSlug}/source/start:
      post:
         consumes:
         - "application/json"
         - "application/xml"
         produces:
         - "application/json"
         responses:
            404:
               description: "Not Found"
            405:
               description: "Validation Error: some given arguments were incorrect"
   /channel/{channelSlug}/source/stop:
      post:
         consumes:
         - "application/json"
         - "application/xml"
         produces:
         - "application/json"
         responses:
            404:
               description: "Not Found"
            405:
               description: "Validation Error: some given arguments were incorrect"
   /source:
      get:
         consumes:
         - "application/json"
         - "application/xml"
         produces:
         - "application/json"
         responses:
            404:
               description: "Not Found"
            405:
               description: "Validation Error: some given arguments were incorrect"
      post:
         consumes:
         - "application/json"
         - "application/xml"
         produces:
         - "application/json"
         responses:
            404:
               description: "Not Found"
            405:
               description: "Validation Error: some given arguments were incorrect"
      put:
         consumes:
         - "application/json"
         - "application/xml"
         produces:
         - "application/json"
         responses:
            404:
               description: "Not Found"
            405:
               description: "Validation Error: some given arguments were incorrect"
      delete:
         consumes:
         - "application/json"
         - "application/xml"
         produces:
         - "application/json"
         responses:
            404:
               description: "Not Found"
            405:
               description: "Validation Error: some given arguments were incorrect"
   /source/{sourceName}:
      get:
         consumes:
         - "application/json"
         - "application/xml"
         produces:
         - "application/json"
         responses:
            404:
               description: "Not Found"
            405:
               description: "Validation Error: some given arguments were incorrect"
      post:
         consumes:
         - "application/json"
         - "application/xml"
         produces:
         - "application/json"
         responses:
            404:
               description: "Not Found"
            405:
               description: "Validation Error: some given arguments were incorrect"
      put:
         consumes:
         - "application/json"
         - "application/xml"
         produces:
         - "application/json"
         responses:
            404:
               description: "Not Found"
            405:
               description: "Validation Error: some given arguments were incorrect"
      delete:
         consumes:
         - "application/json"
         - "application/xml"
         produces:
         - "application/json"
         responses:
            404:
               description: "Not Found"
            405:
               description: "Validation Error: some given arguments were incorrect"
   /source/{sourceName}/start:
      post:
         consumes:
         - "application/json"
         - "application/xml"
         produces:
         - "application/json"
         responses:
            404:
               description: "Not Found"
            405:
               description: "Validation Error: some given arguments were incorrect"
   /source/{sourceName}/stop:
      post:
         consumes:
         - "application/json"
         - "application/xml"
         produces:
         - "application/json"
         responses:
            404:
               description: "Not Found"
            405:
               description: "Validation Error: some given arguments were incorrect"
definitions:
   Channel:
      type: "object"
      properties:
         slug:
            type: "string"
         name:
            type: "string"
         description:
            type: "string"
         active:
            type: "boolean"
            default: true
         deleted:
            type: "boolean"
            default: false
         source:
            $ref: "#/definitions/Source"
   Source:
      type: "object"
      properties:
         name:
            type: "string"
         channel:
            type: "string"
         status:
            type: "string"
            enum:
            - "non-existent"
            - "in-error"
            - "stopped"
            - "playing"
stream_mountpoint:
  type: "string"
